library IEEE;
use ieee.std_logic_1164.all; 
use ieee.numeric_std.ALL;
use ieee.std_logic_unsigned.all; 
use work.CustomDataTypes.all;
use work.AXI_Bus_Package.all;

entity topmod_tb is
--  Port ( );
end topmod_tb;

architecture Behavioral of topmod_tb is

component topmod is
    port (
        --
        -- Clocking and reset ports. sysClk and adcClk are nominally the same frequency
        -- but they aren't synchronized, so treat them as separate clock domains.
        -- adcClkx2 is synchronized to adcClk, but at 2x the frequency.
        -- aresetn is an active-low asynchronous reset
        --
        sysClk          :   in  std_logic;  -- System clock generated by processing system. Synchronous with AXI bus
        adcClk          :   in  std_logic;  -- ADC clock generated by on-board oscillator
        adcClkx2        :   in  std_logic;  -- 2x ADC clock generated usign on-chip logic from ADC clock
        aresetn         :   in  std_logic;  -- Asynchronous reset generated by processing system
        --
        -- These are the I/O signals needed to communicate to the stripped-down
        -- AXI communication system
        --
        addr_i          :   in  unsigned(AXI_ADDR_WIDTH - 1 downto 0);          --Address out
        writeData_i     :   in  std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);  --Data to write
        dataValid_i     :   in  std_logic_vector(1 downto 0);                   --Data valid out signal
        readData_o      :   out std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);  --Data to read
        resp_o          :   out std_logic_vector(1 downto 0);                   --Response in
        --
        -- These are I/O needed to communicate with the XADC system in order to access
        -- the "slow" analog inputs.  They can also be used to read various on-chip
        -- monitoring systems, like a temperature monitor.  DRP stands for Dynamic Reconfiguration Port, and
        -- it can read from/written to just like a memory
        --
        m_drp_den       :   out std_logic;                      -- Enable the DRP port for R/W operations
        m_drp_dwe       :   out std_logic;                      -- Enable a write operation
        m_drp_drdy      :   in  std_logic;                      -- Data is ready on the DIN port
        m_drp_do        :   out std_logic_vector(15 downto 0);  -- Data to be written (data output)
        m_drp_din       :   in  std_logic_vector(15 downto 0);  -- Data to be read (data input)
        m_drp_addr      :   out std_logic_vector(6 downto 0);   -- Address to write to/read from
        --
        -- These are I/O connected to the extension headers E1 and E2,
        -- as well as the LED control
        ext_i           :   in  std_logic_vector(7 downto 0);   -- External inputs, labelled as DIO*_N on E1
        ext_o           :   out std_logic_vector(7 downto 0);   -- External outputs, labelled as DIO*_P on E1
        led_o           :   out std_logic_vector(7 downto 0);   -- LED control, bits correspond to labels on board
        pwm_o           :   out std_logic_vector(3 downto 0);   -- Pulse-width modulation (PWM) control, labelled as Analog Output 0-3 on E2
        --
        -- These are the signals controlling the fast analog inputs and outputs
        --
        adcData_i       :   in  std_logic_vector(31 downto 0);
        m_axis_tdata    :   out std_logic_vector(31 downto 0);
        m_axis_tvalid   :   out std_logic
    );
end component;

component AXI_Tester is
    port (
        --
        -- Clocking and reset
        --
        clk         :   in  std_logic;
        aresetn     :   in  std_logic;
        --
        -- Main AXI data to transfer
        --
        axi_addresses   :   in  t_axi_addr_array;
        axi_data        :   in  t_axi_data_array;
        start_i         :   in  std_logic;
        --
        -- Single data to transfer
        --
        axi_addr_single :   in  t_axi_addr;
        axi_data_single :   in  t_axi_data;
        start_single_i  :   in  std_logic_vector(1 downto 0);
        --
        -- Signals
        --
        bus_m           :   out t_axi_bus_master;
        bus_s           :   in  t_axi_bus_slave
    );
end component;

--
-- Clocks and reset
--
signal clk_period   :   time    :=  10 ns;
signal sysClk,adcClk, adcClkx2:   std_logic;
signal aresetn      :   std_logic;
--
-- ADC and DAC data
--
signal adcData_i    :   std_logic_vector(31 downto 0);
signal m_axis_tdata :   std_logic_vector(31 downto 0);
signal m_axis_tvalid:   std_logic;
--
-- External inputs and outputs
--
signal ext_i,ext_o, led_o  :   std_logic_vector(7 downto 0);
signal pwm_o    :   std_logic_vector(3 downto 0);
--
-- AXI signals
--
signal addr_i                   :   unsigned(AXI_ADDR_WIDTH-1 downto 0);
signal writeData_i, readData_o  :   std_logic_vector(AXI_DATA_WIDTH-1 downto 0);
signal dataValid_i, resp_o      :   std_logic_vector(1 downto 0);
signal bus_m                    :   t_axi_bus_master;
signal bus_s                    :   t_axi_bus_slave;
--
-- DRP signals
--
signal m_drp_den       :   std_logic;                      -- Enable the DRP port for R/W operations
signal m_drp_dwe       :   std_logic;                      -- Enable a write operation
signal m_drp_drdy      :   std_logic;                      -- Data is ready on the DIN port
signal m_drp_do        :   std_logic_vector(15 downto 0);  -- Data to be written (data output)
signal m_drp_din       :   std_logic_vector(15 downto 0);  -- Data to be read (data input)
signal m_drp_addr      :   std_logic_vector(6 downto 0);   -- Address to write to/read from
--
-- AXI data
--

constant axi_addresses   :   t_axi_addr_array(3 downto 0)  :=   (0  =>  X"00000000",
                                                                 1  =>  X"00000004",
                                                                 2  =>  X"03000000",
                                                                 3  =>  X"04000000");

signal axi_data :   t_axi_data_array(axi_addresses'length - 1 downto 0);          

signal triggers, outputReg          :   t_param_reg;
signal test_reg_1                   :   t_param_reg;
signal test_reg_2                   :   t_param_reg;

--
-- AXI control signals
--
signal startAXI     :   std_logic;
signal axi_addr_single  :   t_axi_addr;
signal axi_data_single  :   t_axi_data;
signal start_single_i   :   std_logic_vector(1 downto 0);

begin

clk_proc: process is
begin
    sysClk <= '0';
    adcClk <= '0';
    wait for clk_period/2;
    sysClk <= '1';
    adcClk <= '1';
    wait for clk_period/2;
end process;

clk_procx2: process is
begin
    adcClkx2 <= '0';
    wait for clk_period/4;
    adcClkx2 <= '1';
    wait for clk_period/4;
end process;

uut: topmod
port map(
    sysclk          =>  sysclk,
    adcclk          =>  adcclk,
    adcClkx2        =>  adcClkx2,
    aresetn         =>  aresetn,
    addr_i          =>  addr_i,
    writeData_i     =>  writeData_i,
    dataValid_i     =>  dataValid_i,
    readData_o      =>  readData_o,
    resp_o          =>  resp_o,
    m_drp_den       =>  m_drp_den,
    m_drp_dwe       =>  m_drp_dwe,
    m_drp_drdy      =>  m_drp_drdy,
    m_drp_do        =>  m_drp_do,
    m_drp_din       =>  m_drp_din,
    m_drp_addr      =>  m_drp_addr,
    ext_i           =>  ext_i,
    ext_o           =>  ext_o,
    led_o           =>  led_o,
    pwm_o           =>  pwm_o,
    m_axis_tdata    =>  m_axis_tdata,
    m_axis_tvalid   =>  m_axis_tvalid,
    adcData_i       =>  adcData_i
);

AXI: AXI_Tester
port map(
    clk             =>  sysClk,
    aresetn         =>  aresetn,
    axi_addresses   =>  axi_addresses,
    axi_data        =>  axi_data,
    start_i         =>  startAXI,
    axi_addr_single =>  axi_addr_single,
    axi_data_single =>  axi_data_single,
    start_single_i  =>  start_single_i,
    bus_m           =>  bus_m,
    bus_s           =>  bus_s
);
addr_i <= bus_m.addr;
writeData_i <= bus_m.data;
dataValid_i <= bus_m.valid;
bus_s.data <= readData_o;
bus_s.resp <= resp_o;
--
-- DRP signals
--
m_drp_drdy <= '0';
m_drp_din <= (others => '0');

--
-- Assign AXI registers
--
axi_data <= (0  =>  triggers,
             1  =>  outputReg,
             2  =>  test_reg_1,
             3  =>  test_reg_2
             );

adcData_i <= m_axis_tdata;

main_proc: process is
begin
    --
    -- Initialize the registers and reset
    --
    aresetn <= '0';
    wait for 50 ns;
    startAXI <= '0';
    ext_i <= (others => '0');
    triggers <= (others => '0');
    outputReg <= (others => '0');
    test_reg_1 <= X"76543210";
    test_reg_2 <= X"01234567";
    
    axi_addr_single <= (others => '0');
    axi_data_single <= (others => '0');
    start_single_i <= "00";
    wait for 200 ns;
    aresetn <= '1';
    wait for 100 ns;
    --
    -- Start AXI transfer
    --
    wait until rising_edge(sysclk);
    startAXI <= '1';
    wait until rising_edge(sysclk);
    startAXI <= '0';
    wait for 1 us;
    --
    -- Test reading
    --
    wait until rising_edge(sysclk);
    axi_addr_single <= X"0300_0000";
    axi_data_single <= X"00000000";
    start_single_i <= "10";
    wait until bus_s.resp(0) = '1';
    start_single_i <= "00";
    wait for 500 ns;
    --
    -- Test reading
    --
    wait until rising_edge(sysclk);
    axi_addr_single <= X"0000_0000";
    axi_data_single <= X"00000000";
    start_single_i <= "10";
    wait until bus_s.resp(0) = '1';
    start_single_i <= "00";
    wait for 500 ns;


    wait;
end process; 


end Behavioral;
