library IEEE;
use ieee.std_logic_1164.all; 
use ieee.numeric_std.ALL;
use ieee.std_logic_unsigned.all; 
use work.CustomDataTypes.all;
use work.AXI_Bus_Package.all;

--
-- Example top-level module for parsing simple AXI instructions from the user, and
-- then interfacing those commands with the programmable logic and input/output ports
--
entity topmod is
    port (
        --
        -- Clocking and reset ports. sysClk and adcClk are nominally the same frequency
        -- but they aren't synchronized, so treat them as separate clock domains.
        -- adcClkx2 is synchronized to adcClk, but at 2x the frequency.
        -- aresetn is an active-low asynchronous reset
        --
        sysClk          :   in  std_logic;  -- System clock generated by processing system. Synchronous with AXI bus
        adcClk          :   in  std_logic;  -- ADC clock generated by on-board oscillator
        adcClkx2        :   in  std_logic;  -- 2x ADC clock generated usign on-chip logic from ADC clock
        aresetn         :   in  std_logic;  -- Asynchronous reset generated by processing system
        --
        -- These are the I/O signals needed to communicate to the stripped-down
        -- AXI communication system
        --
        addr_i          :   in  unsigned(AXI_ADDR_WIDTH - 1 downto 0);          --Address out
        writeData_i     :   in  std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);  --Data to write
        dataValid_i     :   in  std_logic_vector(1 downto 0);                   --Data valid out signal
        readData_o      :   out std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);  --Data to read
        resp_o          :   out std_logic_vector(1 downto 0);                   --Response in
        --
        -- These are I/O needed to communicate with the XADC system in order to access
        -- the "slow" analog inputs.  They can also be used to read various on-chip
        -- monitoring systems, like a temperature monitor.  DRP stands for Dynamic Reconfiguration Port, and
        -- it can read from/written to just like a memory
        --
        m_drp_den       :   out std_logic;                      -- Enable the DRP port for R/W operations
        m_drp_dwe       :   out std_logic;                      -- Enable a write operation
        m_drp_drdy      :   in  std_logic;                      -- Data is ready on the DIN port
        m_drp_do        :   out std_logic_vector(15 downto 0);  -- Data to be written (data output)
        m_drp_din       :   in  std_logic_vector(15 downto 0);  -- Data to be read (data input)
        m_drp_addr      :   out std_logic_vector(6 downto 0);   -- Address to write to/read from
        --
        -- These are I/O connected to the extension headers E1 and E2,
        -- as well as the LED control
        ext_i           :   in  std_logic_vector(7 downto 0);   -- External inputs, labelled as DIO*_N on E1
        ext_o           :   out std_logic_vector(7 downto 0);   -- External outputs, labelled as DIO*_P on E1
        led_o           :   out std_logic_vector(7 downto 0);   -- LED control, bits correspond to labels on board
        pwm_o           :   out std_logic_vector(3 downto 0);   -- Pulse-width modulation (PWM) control, labelled as Analog Output 0-3 on E2
        --
        -- These are the signals controlling the fast analog inputs and outputs
        --
        adcData_i       :   in  std_logic_vector(31 downto 0);
        m_axis_tdata    :   out std_logic_vector(31 downto 0);
        m_axis_tvalid   :   out std_logic
    );
end topmod;


architecture Behavioural of topmod is

ATTRIBUTE X_INTERFACE_INFO : STRING;
ATTRIBUTE X_INTERFACE_INFO of m_axis_tdata: SIGNAL is "xilinx.com:interface:axis:1.0 m_axis TDATA";
ATTRIBUTE X_INTERFACE_INFO of m_axis_tvalid: SIGNAL is "xilinx.com:interface:axis:1.0 m_axis TVALID";
ATTRIBUTE X_INTERFACE_PARAMETER : STRING;
ATTRIBUTE X_INTERFACE_PARAMETER of m_axis_tdata: SIGNAL is "CLK_DOMAIN system_AXIS_Red_Pitaya_ADC_0_0_adc_clk,FREQ_HZ 125000000";
ATTRIBUTE X_INTERFACE_PARAMETER of m_axis_tvalid: SIGNAL is "CLK_DOMAIN system_AXIS_Red_Pitaya_ADC_0_0_adc_clk,FREQ_HZ 125000000";

COMPONENT BlockMemory
  PORT (
    clka : IN STD_LOGIC;
    wea : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    addra : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    dina : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    douta : OUT STD_LOGIC_VECTOR(31 DOWNTO 0)
  );
END COMPONENT;

component PWM_Generator is
    port(
        --
        -- Clocking
        --
        clk         :   in  std_logic;
        aresetn     :   in  std_logic;
        --
        -- Input/outputs
        --
        data_i      :   in  t_pwm_array;
        pwm_o       :   out std_logic_vector   
    );
end component;

component TestSubModule is
    port (
        clk     :   in  std_logic;
        aresetn :   in  std_logic;

        bus_m   :   in  t_axi_bus_master;
        bus_s   :   out t_axi_bus_slave
    );
end component;

--
-- AXI communication signals
--
signal comState             :   t_status                        :=  idle;
signal bus_m                :   t_axi_bus_master                :=  INIT_AXI_BUS_MASTER;
signal bus_s                :   t_axi_bus_slave                 :=  INIT_AXI_BUS_SLAVE;
signal reset                :   std_logic;
--
-- Registers
--
signal triggers             :   t_param_reg;
signal outputReg            :   t_param_reg;
signal dac_o                :   t_param_reg;
signal pwmReg               :   t_param_reg;
--
-- Block memory signals
--
signal wea          :   std_logic_vector(0 downto 0);
signal addra        :   std_logic_vector(7 downto 0);
signal dina, douta  :   std_logic_vector(31 downto 0);
signal memDelay     :   unsigned(1 downto 0);
--
-- PWM signals
--
signal pwm_data     :   t_pwm_array(3 downto 0); 
--
-- XADC interface signals
--
signal drp_p        :   t_drp_bus_primary;
signal drp_s        :   t_drp_bus_secondary;

--
-- Submodule signals
--
type t_axi_bus_master_array is array(natural range <>) of t_axi_bus_master;
type t_axi_bus_slave_array is array(natural range <>) of t_axi_bus_slave;

signal subs_bus_m   :   t_axi_bus_master_array(1 downto 0);
signal subs_bus_s   :   t_axi_bus_slave_array(1 downto 0);

begin

--
-- DAC Outputs.  These are put inside a process to properly connect the different clock domains
--
CDC_DAC: process(adcClk,aresetn) is
begin
    if aresetn = '0' then
        m_axis_tdata <= (others => '0');
    elsif rising_edge(adcClk) then
        m_axis_tdata <= dac_o;
    end if;
end process;
m_axis_tvalid <= '1';
--
-- Digital outputs
--
ext_o <= outputReg(7 downto 0);
led_o <= outputReg(15 downto 8);
--
-- Block memory
--
BM : BlockMemory
PORT MAP (
    clka    => sysClk,
    wea     => wea,
    addra   => addra,
    dina    => dina,
    douta   => douta
);
--
-- PWM outputs.  These are put inside a process to properly connect the different clock domains
--
CDC_PWM: process(adcClkx2,aresetn) is
begin
    if aresetn = '0' then
        pwm_data(3 downto 0) <= (others => (others => '0'));
    elsif rising_edge(adcClkx2) then
        pwm_data(0) <= unsigned(pwmReg(7 downto 0));
        pwm_data(1) <= unsigned(pwmReg(15 downto 8));
        pwm_data(2) <= unsigned(pwmReg(23 downto 16));
        pwm_data(3) <= unsigned(pwmReg(31 downto 24));
    end if;
end process;

PWM1: PWM_Generator
port map(
    clk     =>  adcClkx2,
    aresetn =>  aresetn,
    data_i  =>  pwm_data,
    pwm_o   =>  pwm_o
);
--
-- Submodule testing
--
SubModuleGen: for I in 0 to subs_bus_m'length - 1 generate
    SubModuleX: TestSubModule
    port map(
        clk     =>  sysClk,
        aresetn =>  aresetn,
        bus_m   =>  subs_bus_m(I),
        bus_s   =>  subs_bus_s(I)
    );
end generate SubModuleGen;
--
-- AXI communication routing - connects bus objects to std_logic signals
--
bus_m.addr <= addr_i;
bus_m.valid <= dataValid_i;
bus_m.data <= writeData_i;
readData_o <= bus_s.data;
resp_o <= bus_s.resp;

m_drp_den <= drp_p.den;
m_drp_dwe <= drp_p.dwe;
m_drp_do <= drp_p.dout;
m_drp_addr <= drp_p.addr;
drp_s.din <= m_drp_din;
drp_s.drdy <= m_drp_drdy;

Parse: process(sysClk,aresetn) is
begin
    if aresetn = '0' then
        --
        -- Reset all signals to some default value
        --
        comState <= idle;
        reset <= '0';
        bus_s <= INIT_AXI_BUS_SLAVE;
        triggers <= (others => '0');
        outputReg <= (others => '0');
        dac_o <= (others => '0');
        pwmReg <= (others => '0');
        addra <= (others => '0');
        dina <= (others => '0');
        memDelay <= (others => '0');
        wea <= "0";
        drp_p <= DRP_BUS_PRIMARY_INIT;
        for I in 0 to subs_bus_m'length - 1 loop
            subs_bus_m(I) <= INIT_AXI_BUS_MASTER;
        end loop;
    elsif rising_edge(sysClk) then
        FSM: case(comState) is
            --
            -- During the idle phase we wait for a new bus request
            --
            when idle =>
                triggers <= (others => '0');
                reset <= '0';
                drp_p.count <= (others => '0');
                bus_s.resp <= "00";
                for I in 0 to subs_bus_m'length - 1 loop
                    subs_bus_m(I) <= INIT_AXI_BUS_MASTER;
                end loop;
                memDelay <= "00";
                if bus_m.valid(0) = '1' then
                    comState <= processing;
                end if;
            --
            -- Once a bus request is received, we process based on the address
            --
            when processing =>
                AddrCase: case(bus_m.addr(31 downto 24)) is
                    --
                    -- Parameter parsing
                    --
                    when X"00" =>
                        ParamCase: case(bus_m.addr(23 downto 0)) is
                            when X"000000" => rw(bus_m,bus_s,comState,triggers);
                            when X"000004" => rw(bus_m,bus_s,comState,outputReg);
                            when X"000008" => rw(bus_m,bus_s,comState,dac_o);
                            when X"00000C" => readOnly(bus_m,bus_s,comState,adcData_i);
                            when X"000010" => readOnly(bus_m,bus_s,comState,ext_i);
                            when X"000014" => rw(bus_m,bus_s,comState,pwmReg);
                            when others => 
                                comState <= finishing;
                                bus_s.resp <= "11";
                        end case;
                        
                    --
                    -- Read from/write to memory
                    --
                    when X"01" =>
                        addra <= std_logic_vector(bus_m.addr(addra'length + 1 downto 2));
                        if bus_m.valid(1) = '0' then
                            --
                            -- If writing data, route input address and data to memory
                            --
                            comState <= finishing;
                            dina <= bus_m.data;
                            wea <= "1";
                            bus_s.resp <= "01";
                        else
                            --
                            -- If reading from memory, we need an extra 2 wait cycles
                            --
                            if memDelay = "00" then
                                memDelay <= "11";
                            elsif memDelay > "01" then
                                memDelay <= memDelay - 1;
                            else
                                bus_s.data <= douta;
                                bus_s.resp <= "01";
                                comState <= finishing;
                            end if;
                        end if;
                        
                    --
                    -- Read/write from XADC via DRP
                    --
                    when X"02" => rw(bus_m,bus_s,comState,drp_p,drp_s);

                    --
                    -- Test multi-module parsing
                    --
                    when X"03" => rw_sub_mod(bus_m,bus_s,comState,subs_bus_m(0),subs_bus_s(0));
                    when X"04" => rw_sub_mod(bus_m,bus_s,comState,subs_bus_m(1),subs_bus_s(1));

                    when others => 
                        comState <= finishing;
                        bus_s.resp <= "11";
                end case;
            --
            -- Finish up with data processing
            --
            when finishing =>
                wea <= "0";
                comState <= idle;
                drp_p.dwe <= '0';
                drp_p.den <= '0';

            when others => comState <= idle;
        end case;
    end if;
end process;

    
end architecture Behavioural;